mybatis:
  #指定xml映射文件位置，多个时逗号分隔
  mapper-locations: classpath:mapper/**.xml
  #实体类别名，有多个包时以英文逗号或分号隔开
  type-aliases-package: com.ervin.db.entity
  configuration:
    #下划线自动转驼峰
    map-underscore-to-camel-case: true
    #打印sql语句，有多种日志实现方式，常用StdOutImpl、Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

spring:
  datasource:
    #默认就是hikari，可缺省
    #    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root001
    hikari:
      #默认30000 ms，即30s
      connection-timeout: 30000
      #默认600000 ms，即10min
      idle-timeout: 600000
      #连接池中的最大连接数（active+idle），默认10
      maximum-pool-size: 200
      #默认10
      minimum-idle: 50
